//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace caseGuardTest.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string imgPath {
            get {
                return ((string)(this["imgPath"]));
            }
            set {
                this["imgPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.ArrayList thicknessLeft {
            get {
                return ((global::System.Collections.ArrayList)(this["thicknessLeft"]));
            }
            set {
                this["thicknessLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.ArrayList thicknessTop {
            get {
                return ((global::System.Collections.ArrayList)(this["thicknessTop"]));
            }
            set {
                this["thicknessTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.ArrayList thicknessRight {
            get {
                return ((global::System.Collections.ArrayList)(this["thicknessRight"]));
            }
            set {
                this["thicknessRight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.ArrayList thicknessbottom {
            get {
                return ((global::System.Collections.ArrayList)(this["thicknessbottom"]));
            }
            set {
                this["thicknessbottom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.ArrayList thicknessValue {
            get {
                return ((global::System.Collections.ArrayList)(this["thicknessValue"]));
            }
            set {
                this["thicknessValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.ArrayList selectedColorR {
            get {
                return ((global::System.Collections.ArrayList)(this["selectedColorR"]));
            }
            set {
                this["selectedColorR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.ArrayList selectedColorG {
            get {
                return ((global::System.Collections.ArrayList)(this["selectedColorG"]));
            }
            set {
                this["selectedColorG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.ArrayList selectedColorB {
            get {
                return ((global::System.Collections.ArrayList)(this["selectedColorB"]));
            }
            set {
                this["selectedColorB"] = value;
            }
        }
    }
}
